### ISSUE TITLE
Lack of xxx.npy file

### ISSUE THREAD

**Issue by shuli1224** [vbordoux/dcase_task5_Bordoux_WUR#1]
Hello, could you please tell me what the xxx.npy file is? I couldn't find it in the extracted dataset.

**Comment by vbordoux** [comment]
Could you provide me a bit more details on where you have seen mention of this xxx.npy file so I could help you better?

**Comment by shuli1224** [comment]
> Could you provide me a bit more details on where you have seen mention of this xxx.npy file so I could help you better?

Thank you, the issue has been resolved. I encountered an error when running baselines/dcase2024_task5/data_preparation.py:

Traceback (most recent call last):
  File "data_preparation.py", line 279, in <module>
    main(data_path)
  File "data_preparation.py", line 252, in main
    array = np.load(npy_path)
  File "/SATA03/tanyupeng/anaconda3/envs/dacse_base/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/SATA03/tanyupeng/Project/dcase_task5_Bordoux_WUR-main/Datasets/Development_Set/Validation_Set/ME/ME2_mel.npy'

However, I followed the modifications in your method in baselines/my_method/data_preparation.py and successfully generated the .npy file.
